services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - open-webui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  # Optional: MCP Proxy Server for tools
  mcpo-server:
    image: call518/mcpo-server:latest
    container_name: mcpo-server
    ports:
      - "8000:8000"
    volumes:
      - ./mcp-config.json:/app/config/mcp-config.json
      - ./tool-weather:/app/tool-weather
    restart: always

volumes:
  open-webui-data:
    name: open-webui-data
