services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - open-webui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  # Optional: MCP Proxy Server for tools
  mcpo-proxy:
    image: call518/mcpo-proxy:1.0.0
    container_name: mcpo-proxy
    ports:
      - "8000:8000"
    volumes:
      - ./mcp-config.json:/app/config/mcp-config.json
      - ./tools:/app/tools
    restart: always

volumes:
  open-webui-data:
    name: open-webui-data-demo
